### ISSUE TITLE
tsv文件读取失败 pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by shidongshana** [Cyril-JZ/InteR#4]
msmarco run detected. Converting to trec...
Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 540, in _infer_columns
    line = self._buffered_line()
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 630, in _buffered_line
    return self._next_line()
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 731, in _next_line
    orig_line = self._next_iter_line(row_num=self.pos + 1)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 795, in _next_iter_line
    line = next(self.data)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\.conda\envs\inter\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\.conda\envs\inter\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pyserini\eval\trec_eval.py", line 70, in <module>
    run = pd.read_csv(args[-1], delim_whitespace=True, engine='python', header=None)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 124, in __init__
    ) = self._infer_columns()
  File "C:\Users\admin\.conda\envs\inter\lib\site-packages\pandas\io\parsers\python_parser.py", line 544, in _infer_columns
    raise EmptyDataError("No columns to parse from file") from err
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by Cyril-JZ** [comment]
Hi, could you please set `--eval_bm25` as True to ensure that the evaluation scripts from [Pyserini] (https://github.com/castorini/pyserini) is still valid.
